# Generated by Django 6.0.3 on 2026-04-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=10),
        ),
    ]
